---
development:
  dialect: mysql
  database: {{ envOr "ARCHER_DATABASE" "archer" }}
  user: {{ envOr "ARCHER_DATABASE_USER" "archer" }}
  password: {{ envOr "ARCHER_DATABASE_PASSWORD" "archer" }}
  host: {{ envOr "ARCHER_DATABASE_HOST" "127.0.0.1" }}
  port: {{ envOr "ARCHER_DATABASE_PORT" "8135" }}
  pool: 5

test:
  dialect: "sqlite3"
  database: ./test.sqlite

production:
  dialect: mysql
  database: {{ envOr "ARCHER_DATABASE" "archer" }}
  user: {{ envOr "ARCHER_DATABASE_USER" "archer" }}
  password: {{ envOr "ARCHER_DATABASE_PASSWORD" "archer" }}
  host: {{ envOr "ARCHER_DATABASE_HOST" "127.0.0.1" }}
  port: {{ envOr "ARCHER_DATABASE_PORT" "8135" }}
  pool: 5
